from __future__ import annotations
"""
Triage & Synthesis Agent  (Agent 4)
--------------------------------------
Responsibilities:
  - Combine symptom_assessment (Agent 2) and image_assessment (Agent 3) from state
  - Use UrgencyCalculatorTool (deterministic) to derive urgency / agreement as a
    grounded safety anchor — the LLM cannot override these values
  - Use the LLM to reason over both assessments in plain language: explain whether
    they agree or conflict, interpret confidence and uncertainty flags, and write a
    clear, structured final report with next-step recommendations
  - The LLM must NOT invent new diagnoses or contradict the ML agents' predictions;
    it works strictly with what Agents 2 and 3 returned
  - Populate: triage_result, final_report, uncertainty_flags, possible_out_of_scope
"""

import json
import logging
from typing import Any, Dict

from app.llm.ollama_client import chat_json
from app.observability.logger import log_event
from app.state.schema import PetCaseState
from app.tools.triage_tools import UrgencyCalculatorTool

logger = logging.getLogger(__name__)

_tool = UrgencyCalculatorTool()

_DISCLAIMER = (
    "This report is generated by an AI-assisted triage system and is NOT a "
    "substitute for professional veterinary advice, diagnosis, or treatment. "
    "Always consult a qualified veterinarian."
)


_VALID_URGENCY = {"urgent", "vet_soon", "monitor", "non-urgent"}


# ── LLM prompt ────────────────────────────────────────────────────────────────

def _build_llm_messages(
    pet_profile:         Dict[str, Any],
    symptom_assessment:  Dict[str, Any],
    image_assessment:    Dict[str, Any],
    tool_urgency:        str,
    tool_agreement:      str,
    tool_uncertainty:    str,
    tool_recommendation: str,
) -> list:
    """
    Build the system + user messages that ask the LLM to reason over the two
    ML assessments and produce a structured triage report.

    The LLM is given the deterministic urgency level and agreement status as
    ground truth — it explains and elaborates but cannot change them.
    """
    has_image = bool(image_assessment) and image_assessment.get("image_validity") not in (
        "none", "unusable", "error", "", None
    )

    sym_pred = symptom_assessment.get("top_prediction", "unknown")
    sym_conf = symptom_assessment.get("confidence", 0.0)
    sym_alts = symptom_assessment.get("alternatives", [])
    img_pred = image_assessment.get("image_prediction", "") if has_image else "N/A"
    img_conf = image_assessment.get("confidence", 0.0)      if has_image else 0.0
    img_valid = image_assessment.get("image_validity", "none")

    system_prompt = (
        "You are Agent 4, the Triage & Synthesis agent in a veterinary AI system.\n\n"
        "Your job:\n"
        "  1. Reason over the outputs from Agent 2 (symptom ML model) and Agent 3 "
        "(image CNN model) that are provided below.\n"
        "  2. Explain in clear, plain language whether the two models AGREE, CONFLICT, "
        "or indicate separate issues — and what that means for the pet owner.\n"
        "  3. Interpret the confidence scores and uncertainty flags.\n"
        "  4. Write a concise recommendation and next-steps explanation.\n\n"
        "STRICT RULES — you must follow all of these:\n"
        "  - Do NOT invent or suggest any diagnosis not already present in the ML outputs.\n"
        "  - Do NOT change the urgency_level — it has already been calculated by a "
        "deterministic safety tool and is given to you as fixed ground truth.\n"
        "  - Do NOT override or contradict Agent 2's or Agent 3's predictions.\n"
        "  - Write for a worried pet owner — be calm, clear, and empathetic.\n"
        "  - Return ONLY valid JSON matching the schema below. No markdown, no extra text.\n\n"
        "Output schema (return exactly this structure):\n"
        "{\n"
        '  "summary": "2-3 sentence plain-language summary of the situation",\n'
        '  "agreement_explanation": "1-2 sentences explaining whether agents agree/conflict and why it matters",\n'
        '  "confidence_explanation": "1 sentence interpreting confidence and uncertainty",\n'
        '  "recommendation": "Clear, actionable recommendation for the pet owner",\n'
        '  "next_steps": "Specific next actions the owner should take",\n'
        '  "reasoning": "1 sentence technical trace: what each model predicted and why urgency was assigned"\n'
        "}"
    )

    image_section = (
        f"  - Image model prediction : {img_pred} (confidence: {img_conf:.0%})\n"
        f"  - Image validity         : {img_valid}\n"
        if has_image
        else "  - Image assessment       : No valid image was provided for this case.\n"
    )

    user_prompt = (
        f"Pet profile: {json.dumps(pet_profile)}\n\n"
        "=== Agent 2 — Symptom ML Assessment ===\n"
        f"  - Top prediction         : {sym_pred} (confidence: {sym_conf:.0%})\n"
        f"  - Alternative conditions : {sym_alts}\n"
        f"  - Uncertainty flag       : {symptom_assessment.get('uncertainty_flag', False)}\n"
        f"  - Out-of-scope flag      : {symptom_assessment.get('possible_out_of_scope', False)}\n\n"
        "=== Agent 3 — Image CNN Assessment ===\n"
        f"{image_section}\n"
        "=== Deterministic Safety Anchor (do NOT change these) ===\n"
        f"  - urgency_level   : {tool_urgency}   ← FIXED, do not change\n"
        f"  - agreement_status: {tool_agreement}\n"
        f"  - uncertainty     : {tool_uncertainty}\n"
        f"  - base recommendation: {tool_recommendation}\n\n"
        "Now produce the JSON triage report following the schema in the system prompt."
    )

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": user_prompt},
    ]


# ── Main entry point ───────────────────────────────────────────────────────────

def run(state: PetCaseState) -> PetCaseState:
    """
    Run Agent 4 — Triage & Case Synthesis.

    Step 1: UrgencyCalculatorTool runs deterministically — produces urgency_level,
            agreement_status, uncertainty_status as grounded safety outputs.
    Step 2: LLM reasons over both ML assessments using those fixed values as anchors
            — produces plain-language summary, agreement explanation, confidence
            interpretation, recommendation, and next steps.
    Step 3: Results are merged into triage_result + final_report and written to state.
    """
    symptom_assessment: Dict[str, Any] = state.get("symptom_assessment") or {}
    image_assessment:   Dict[str, Any] = state.get("image_assessment")   or {}
    pet_profile:        Dict[str, Any] = state.get("pet_profile")        or {}

    logger.info(
        "[Agent4] Starting triage | sym_status=%s img_validity=%s",
        symptom_assessment.get("assessment_status"),
        image_assessment.get("image_validity", "none"),
    )

    # ── Step 1: Deterministic tool — safety anchor ────────────────────────────
    tool_input = json.dumps({
        "symptom_result": symptom_assessment,
        "image_result":   image_assessment,
    })
    tool_output_raw = _tool._run(tool_input)
    tool_triage: Dict[str, Any] = json.loads(tool_output_raw)

    urgency_level       = tool_triage.get("urgency_level",      "monitor")
    uncertainty_status  = tool_triage.get("uncertainty_status", "uncertain")
    agreement_status    = tool_triage.get("agreement_status",   "none")
    base_recommendation = tool_triage.get("recommendation",     "Please consult a veterinarian.")
    base_reasoning      = tool_triage.get("reasoning",          "")

    logger.info(
        "[Agent4] Tool anchor: urgency=%s agreement=%s uncertainty=%s",
        urgency_level, agreement_status, uncertainty_status,
    )

    # ── Step 2: LLM reasoning & report generation ─────────────────────────────
    llm_summary                = ""
    llm_agreement_explanation  = ""
    llm_confidence_explanation = ""
    llm_recommendation         = base_recommendation
    llm_next_steps             = _next_steps(urgency_level)
    llm_reasoning              = base_reasoning

    try:
        messages   = _build_llm_messages(
            pet_profile         = pet_profile,
            symptom_assessment  = symptom_assessment,
            image_assessment    = image_assessment,
            tool_urgency        = urgency_level,
            tool_agreement      = agreement_status,
            tool_uncertainty    = uncertainty_status,
            tool_recommendation = base_recommendation,
        )
        llm_result = chat_json(messages, temperature=0.2)

        if isinstance(llm_result, dict) and "summary" in llm_result:
            llm_summary                = llm_result.get("summary",                "")
            llm_agreement_explanation  = llm_result.get("agreement_explanation",  "")
            llm_confidence_explanation = llm_result.get("confidence_explanation", "")
            llm_recommendation         = llm_result.get("recommendation", base_recommendation) or base_recommendation
            llm_next_steps             = llm_result.get("next_steps",     llm_next_steps)      or llm_next_steps
            llm_reasoning              = llm_result.get("reasoning",      base_reasoning)       or base_reasoning
            logger.info("[Agent4] LLM synthesis complete")
        else:
            logger.warning("[Agent4] LLM returned unexpected shape — using deterministic fallback")

    except Exception as exc:
        logger.warning("[Agent4] LLM call failed (%s) — falling back to deterministic output", exc)

    # ── Step 3: Build triage_result ───────────────────────────────────────────
    triage_result: Dict[str, Any] = {
        "primary_assessment":  symptom_assessment.get("top_prediction", "unknown"),
        "urgency_level":       urgency_level,        # always from tool — LLM cannot change this
        "recommendation":      llm_recommendation,
        "uncertainty_status":  uncertainty_status,
        "agreement_status":    agreement_status,
        "reasoning":           llm_reasoning,
        "confidence":          symptom_assessment.get("confidence", 0.0),
        "alternatives":        symptom_assessment.get("alternatives", []),
        "image_prediction":    image_assessment.get("image_prediction", ""),
        "image_validity":      image_assessment.get("image_validity", "none"),
    }

    # ── Step 4: Build final_report ─────────────────────────────────────────────
    final_report: Dict[str, Any] = {
        "pet_profile": pet_profile,
        "triage_summary": {
            "likely_condition":        symptom_assessment.get("top_prediction", "unknown"),
            "confidence_level":        _confidence_label(symptom_assessment.get("confidence", 0.0)),
            "urgency":                 urgency_level,
            "uncertainty":             uncertainty_status,
            "summary":                 llm_summary,
            "agreement_explanation":   llm_agreement_explanation,
            "confidence_explanation":  llm_confidence_explanation,
        },
        "recommendations": {
            "primary":    llm_recommendation,
            "next_steps": llm_next_steps,
        },
        "supporting_data": {
            "symptom_top_prediction": symptom_assessment.get("top_prediction"),
            "symptom_confidence":     symptom_assessment.get("confidence"),
            "symptom_alternatives":   symptom_assessment.get("alternatives", []),
            "image_prediction":       image_assessment.get("image_prediction"),
            "image_confidence":       image_assessment.get("confidence"),
            "image_validity":         image_assessment.get("image_validity", "none"),
            "agreement_status":       agreement_status,
        },
        "reasoning":  llm_reasoning,
        "disclaimer": _DISCLAIMER,
    }

    # ── Uncertainty flags ──────────────────────────────────────────────────────
    if uncertainty_status in ("uncertain", "conflict", "out_of_scope"):
        state.setdefault("uncertainty_flags", [])
        if uncertainty_status not in state["uncertainty_flags"]:
            state["uncertainty_flags"].append(f"triage_{uncertainty_status}")

    if uncertainty_status == "out_of_scope":
        state["possible_out_of_scope"] = True

    # ── Write back to state ────────────────────────────────────────────────────
    state["triage_result"] = triage_result
    state["final_report"]  = final_report

    # ── Observability trace ────────────────────────────────────────────────────
    trace_event = log_event("triage_agent_completed", {
        "urgency_level":      urgency_level,
        "uncertainty_status": uncertainty_status,
        "agreement_status":   agreement_status,
        "primary_assessment": triage_result["primary_assessment"],
        "llm_used":           bool(llm_summary),
    })
    state.setdefault("trace_events", []).append(trace_event)

    logger.info(
        "[Agent4] Triage complete | urgency=%s uncertainty=%s agreement=%s llm_used=%s",
        urgency_level, uncertainty_status, agreement_status, bool(llm_summary),
    )

    return state


# ── Helpers ────────────────────────────────────────────────────────────────────

def _confidence_label(confidence: float) -> str:
    """Map a float confidence to a human-readable label."""
    if confidence >= 0.65:
        return "high"
    if confidence >= 0.40:
        return "medium"
    return "low"


def _next_steps(urgency_level: str) -> str:
    """Return actionable next-steps text based on urgency."""
    return {
        "urgent":     "Go to an emergency veterinary clinic immediately.",
        "vet_soon":   "Schedule a veterinary appointment within 24–48 hours.",
        "monitor":    "Monitor your pet at home. Visit a vet if symptoms worsen or persist beyond 24 hours.",
        "non-urgent": "No immediate action required. Schedule a routine check-up.",
    }.get(urgency_level, "Consult a veterinarian for guidance.")