from __future__ import annotations
"""
Triage & Synthesis Agent  (Agent 4)
--------------------------------------
Responsibilities:
  - Combine symptom_assessment (Agent 2) and image_assessment (Agent 3) from state
  - Resolve agreement / conflict between the two
  - Assign urgency level: non-urgent | monitor | vet_soon | urgent
  - Generate final structured report with disclaimer
  - Populate: triage_result, final_report, uncertainty_flags, possible_out_of_scope

Tool used: UrgencyCalculatorTool (deterministic — no extra LLM call needed)
"""

import json
import logging
from typing import Any, Dict

from app.observability.logger import log_event
from app.state.schema import PetCaseState
from app.tools.triage_tools import UrgencyCalculatorTool, _classify_urgency

logger = logging.getLogger(__name__)

_tool = UrgencyCalculatorTool()

_DISCLAIMER = (
    "This report is generated by an AI-assisted triage system and is NOT a "
    "substitute for professional veterinary advice, diagnosis, or treatment. "
    "Always consult a qualified veterinarian."
)


def run(state: PetCaseState) -> PetCaseState:
    """
    Run Agent 4 — Triage & Case Synthesis.

    Reads symptom_assessment and image_assessment from state,
    calls UrgencyCalculatorTool, and writes triage_result + final_report
    back into state.

    Args:
        state: Current PetCaseState containing at least symptom_assessment.

    Returns:
        Updated PetCaseState with triage_result and final_report populated.
    """
    symptom_assessment: Dict[str, Any] = state.get("symptom_assessment") or {}
    image_assessment:   Dict[str, Any] = state.get("image_assessment")   or {}
    pet_profile:        Dict[str, Any] = state.get("pet_profile")        or {}

    logger.info(
        "[Agent4] Starting triage | sym_status=%s img_validity=%s",
        symptom_assessment.get("assessment_status"),
        image_assessment.get("image_validity", "none"),
    )

    # ── Call UrgencyCalculatorTool ────────────────────────────────────────────
    tool_input = json.dumps({
        "symptom_result": symptom_assessment,
        "image_result":   image_assessment,
    })

    tool_output_raw = _tool._run(tool_input)
    triage: Dict[str, Any] = json.loads(tool_output_raw)

    urgency_level      = triage.get("urgency_level",      "monitor")
    recommendation     = triage.get("recommendation",     "Please consult a veterinarian.")
    uncertainty_status = triage.get("uncertainty_status", "uncertain")
    agreement_status   = triage.get("agreement_status",   "none")
    reasoning          = triage.get("reasoning",          "")

    # ── Build triage_result ───────────────────────────────────────────────────
    triage_result: Dict[str, Any] = {
        "primary_assessment":  symptom_assessment.get("top_prediction", "unknown"),
        "urgency_level":       urgency_level,
        "recommendation":      recommendation,
        "uncertainty_status":  uncertainty_status,
        "agreement_status":    agreement_status,
        "reasoning":           reasoning,
        "confidence":          symptom_assessment.get("confidence", 0.0),
        "alternatives":        symptom_assessment.get("alternatives", []),
        "image_prediction":    image_assessment.get("image_prediction", ""),
        "image_validity":      image_assessment.get("image_validity", "none"),
    }

    # ── Build final_report ────────────────────────────────────────────────────
    final_report: Dict[str, Any] = {
        "pet_profile":    pet_profile,
        "triage_summary": {
            "likely_condition":   symptom_assessment.get("top_prediction", "unknown"),
            "confidence_level":   _confidence_label(symptom_assessment.get("confidence", 0.0)),
            "urgency":            urgency_level,
            "uncertainty":        uncertainty_status,
        },
        "recommendations": {
            "primary":     recommendation,
            "next_steps":  _next_steps(urgency_level),
        },
        "supporting_data": {
            "symptom_top_prediction":  symptom_assessment.get("top_prediction"),
            "symptom_confidence":      symptom_assessment.get("confidence"),
            "symptom_alternatives":    symptom_assessment.get("alternatives", []),
            "image_prediction":        image_assessment.get("image_prediction"),
            "image_confidence":        image_assessment.get("confidence"),
            "image_validity":          image_assessment.get("image_validity", "none"),
            "agreement_status":        agreement_status,
        },
        "reasoning":   reasoning,
        "disclaimer":  _DISCLAIMER,
    }

    # ── Update uncertainty flags in state ─────────────────────────────────────
    if uncertainty_status in ("uncertain", "conflict", "out_of_scope"):
        state.setdefault("uncertainty_flags", [])
        if uncertainty_status not in state["uncertainty_flags"]:
            state["uncertainty_flags"].append(f"triage_{uncertainty_status}")

    if uncertainty_status == "out_of_scope":
        state["possible_out_of_scope"] = True

    # ── Write back to state ───────────────────────────────────────────────────
    state["triage_result"] = triage_result
    state["final_report"]  = final_report

    # ── Observability trace ───────────────────────────────────────────────────
    trace_event = log_event("triage_agent_completed", {
        "urgency_level":      urgency_level,
        "uncertainty_status": uncertainty_status,
        "agreement_status":   agreement_status,
        "primary_assessment": triage_result["primary_assessment"],
    })
    state.setdefault("trace_events", []).append(trace_event)

    logger.info(
        "[Agent4] Triage complete | urgency=%s uncertainty=%s agreement=%s",
        urgency_level, uncertainty_status, agreement_status,
    )

    return state


# ── Helpers ────────────────────────────────────────────────────────────────────

def _confidence_label(confidence: float) -> str:
    """Map a float confidence to a human-readable label."""
    if confidence >= 0.65:
        return "high"
    if confidence >= 0.40:
        return "medium"
    return "low"


def _next_steps(urgency_level: str) -> str:
    """Return actionable next-steps text based on urgency."""
    return {
        "urgent":     "Go to an emergency veterinary clinic immediately.",
        "vet_soon":   "Schedule a veterinary appointment within 24–48 hours.",
        "monitor":    "Monitor your pet at home. Visit a vet if symptoms worsen or persist beyond 24 hours.",
        "non-urgent": "No immediate action required. Schedule a routine check-up.",
    }.get(urgency_level, "Consult a veterinarian for guidance.")